-- phpMyAdmin SQL Dump
-- version 4.4.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Jun 02, 2019 at 11:41 PM
-- Server version: 5.6.26
-- PHP Version: 5.6.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `knh`
--

-- --------------------------------------------------------

--
-- Table structure for table `career`
--

CREATE TABLE IF NOT EXISTS `career` (
  `count` int(50) NOT NULL,
  `fname` varchar(50) NOT NULL,
  `lname` varchar(50) NOT NULL,
  `email` varchar(20) NOT NULL,
  `phone` int(12) NOT NULL,
  `idnumber` int(12) NOT NULL,
  `age` varchar(10) NOT NULL,
  `gender` char(10) NOT NULL,
  `role` varchar(15) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `career`
--

INSERT INTO `career` (`count`, `fname`, `lname`, `email`, `phone`, `idnumber`, `age`, `gender`, `role`) VALUES
(1, 'a', 'a', 'admin@gmail.com', 0, 0, '', '', ''),
(2, 'Boniface', 'Njugu', 'njugu@gmail.com', 722489562, 678, '25', 'Male', 'approved'),
(3, 'Boniface', 'gathoni', 'ian@gmail.com', 700832711, 2147483647, '12', 'Male', 'career');

-- --------------------------------------------------------

--
-- Table structure for table `donors`
--

CREATE TABLE IF NOT EXISTS `donors` (
  `count` int(50) NOT NULL,
  `allnames` char(100) NOT NULL,
  `nationalid` int(10) NOT NULL,
  `service` char(50) NOT NULL,
  `status` char(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `residence` varchar(50) NOT NULL,
  `phone` int(12) NOT NULL,
  `donorreason` text NOT NULL,
  `bloodgroup` enum('A','B','AB','O') NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `donors`
--

INSERT INTO `donors` (`count`, `allnames`, `nationalid`, `service`, `status`, `email`, `residence`, `phone`, `donorreason`, `bloodgroup`) VALUES
(18, 'john mathew', 4, 'Eyes', 'APPROVED', 'aaaa@gmail.com', 'juja', 715012649, 'i have liver cirrhosis and doctor says i cant live past 2 months.', 'A');

-- --------------------------------------------------------

--
-- Table structure for table `feedback`
--

CREATE TABLE IF NOT EXISTS `feedback` (
  `Count` int(50) NOT NULL,
  `fname` varchar(50) NOT NULL,
  `lname` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `feedback` varchar(1000) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `feedback`
--

INSERT INTO `feedback` (`Count`, `fname`, `lname`, `email`, `feedback`) VALUES
(3, 'loise', 'gathoni', 'loisegatho4858@gmail.com', 'loise'),
(4, 'loise', 'gathoni', 'loisegatho4858@gmail.com', 'loise'),
(5, 'loise', 'gathoni', 'loisegatho4858@gmail.com', 'loise'),
(6, 'loise', 'gathoni', 'loisegatho4858@gmail.com', 'loise'),
(7, 'loise', 'gathoni', 'loisegatho4858@gmail.com', 'loise'),
(8, 'loise', 'gathoni', 'loisegatho4858@gmail.com', 'loise'),
(9, 'loise', 'gathoni', 'loisegatho4858@gmail.com', 'loise'),
(10, 'loise', 'gathoni', 'loisegatho4858@gmail.com', 'a.	Wireframe model-skeleton REPRESENTATION OF  A 3d MODEL\nb.	Surface model- develops objects by stretching a surface over them with 3D curves created by the designer.\nc.	Solid models- REPRESENTATION OF SOLID MODELS in CAD\n2.	Describe the various commands used in drawing a circle\n‘CIRCLE’ COMMAND\n3.	What does the term NURBS stand for and what is its purpose\nNURBS- Non-uniform rational basis spline is the way in which curves are generated by comps.\nNURBS stands for nonuniform rational B-spline curves. A NURBS surface as a 3D spline with fit points. These fit points can be used \n'),
(11, 'q', 'q', 'ian@gmail.com', 'a.	Wireframe model-skeleton REPRESENTATION OF  A 3'),
(12, 'Boniface', 'Njugu', 'njugu@gmail.com', 'YOUR SERVICES ARE ADMIRABLE. THANKS.'),
(13, 'a', 'a', 'admin@gmail.com', 'asas'),
(14, 'a', 'a', 'admin@gmail.com', 'asas'),
(15, 'q', 'ian', '1benpatrick@gmail.com', 'asda');

-- --------------------------------------------------------

--
-- Table structure for table `requests`
--

CREATE TABLE IF NOT EXISTS `requests` (
  `count` int(50) NOT NULL,
  `allnames` char(100) NOT NULL,
  `nationalid` int(10) NOT NULL,
  `service` char(50) NOT NULL,
  `status` char(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `residence` varchar(50) NOT NULL,
  `phone` int(12) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `requests`
--

INSERT INTO `requests` (`count`, `allnames`, `nationalid`, `service`, `status`, `email`, `residence`, `phone`) VALUES
(11, 'ERICK MUTUNGA', 23, 'HEART', 'APPROVED', 'mary@gmail.com', 'THIKA', 7154866),
(12, 'Yoyo Gg', 626260, 'HEART', 'APPROVED', 'yoyo@gmail.com', 'Ruiru', 725841516),
(13, 'claire', 32427061, 'donor', 'pending', 'admin@gmail.com', 'Juja', 2147483647),
(14, 'Simon peter', 12345678, 'Eyes', 'APPROVED', 'simonpeter@gmail.com', 'Nairobi', 712345678);

-- --------------------------------------------------------

--
-- Table structure for table `services`
--

CREATE TABLE IF NOT EXISTS `services` (
  `count` int(50) NOT NULL,
  `services` varchar(50) NOT NULL,
  `cost` int(20) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `services`
--

INSERT INTO `services` (`count`, `services`, `cost`) VALUES
(1, 'Heart', 2500000),
(2, 'Kidney', 2000),
(3, 'Liver', 15000);

-- --------------------------------------------------------

--
-- Table structure for table `staff`
--

CREATE TABLE IF NOT EXISTS `staff` (
  `count` int(100) NOT NULL,
  `fname` varchar(50) NOT NULL,
  `lname` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `phone` int(50) NOT NULL,
  `idnumber` int(20) NOT NULL,
  `age` int(50) NOT NULL,
  `gender` char(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `role` char(10) NOT NULL,
  `login` varchar(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `staff`
--

INSERT INTO `staff` (`count`, `fname`, `lname`, `email`, `phone`, `idnumber`, `age`, `gender`, `password`, `role`, `login`) VALUES
(2, 'patient', 'patient', 'ian@gmail.com', 710814796, 2, 25, 'Male', 'abcd', 'patient', 'yes'),
(3, 'Admin', 'nistrator', 'ian@gmail.com', 710814796, 3, 25, 'Male', 'abcd', 'admin', 'yes'),
(17, 'Yoyo', 'GG', 'gefe@gmail.com', 72515116, 626260, 34, 'Male', '12345', 'patient', 'yes'),
(18, 'donot', 'donor', 'donor@gmail.com', 723344334, 4, 32, '', '1234', 'donor', 'yes'),
(21, 'claire', 'muhoro', 'clairemuhoro@gmail.com', 712198336, 32427061, 25, 'Female', '12345', 'donor', 'yes'),
(22, 'lucy', 'gichia', 'lucyg@gmail.com', 765656543, 43434354, 34, 'Female', '12345', 'patient', 'yes'),
(23, 'Simon', 'Peter', 'simonpeter@gmail.com', 712345678, 12345678, 20, 'Male', '1234567890', 'patient', 'yes');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `career`
--
ALTER TABLE `career`
  ADD PRIMARY KEY (`count`);

--
-- Indexes for table `donors`
--
ALTER TABLE `donors`
  ADD PRIMARY KEY (`count`);

--
-- Indexes for table `feedback`
--
ALTER TABLE `feedback`
  ADD PRIMARY KEY (`Count`);

--
-- Indexes for table `requests`
--
ALTER TABLE `requests`
  ADD PRIMARY KEY (`count`);

--
-- Indexes for table `services`
--
ALTER TABLE `services`
  ADD PRIMARY KEY (`count`);

--
-- Indexes for table `staff`
--
ALTER TABLE `staff`
  ADD PRIMARY KEY (`count`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `career`
--
ALTER TABLE `career`
  MODIFY `count` int(50) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT for table `donors`
--
ALTER TABLE `donors`
  MODIFY `count` int(50) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=19;
--
-- AUTO_INCREMENT for table `feedback`
--
ALTER TABLE `feedback`
  MODIFY `Count` int(50) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=16;
--
-- AUTO_INCREMENT for table `requests`
--
ALTER TABLE `requests`
  MODIFY `count` int(50) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=15;
--
-- AUTO_INCREMENT for table `services`
--
ALTER TABLE `services`
  MODIFY `count` int(50) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT for table `staff`
--
ALTER TABLE `staff`
  MODIFY `count` int(100) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=24;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
